# name: Generate Snake

# on:
#   # run automatically every 24 hours
#   schedule:
#     - cron: "0 0 * * *" 
  
#   # allows to manually run the job at any time
#   workflow_dispatch:
  
#   # run on every push on the master branch
#   push:
#     branches:
#     - master
    
# jobs:
#   generate:
#     runs-on: ubuntu-latest
#     timeout-minutes: 10
    
#     steps:
#       # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
#       - name: generate github-contribution-grid-snake.svg
#         uses: Platane/snk/svg-only@v3
#         with:
#           github_user_name: ${{ github.repository_owner }}
#           outputs: |
#             dist/github-contribution-grid-snake-light.svg
#             dist/github-contribution-grid-snake-night.svg?palette=github-dark
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
#       # push the content of <build_dir> to a branch
#       # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
#       - name: push github-contribution-grid-snake.svg to the output branch
#         uses: crazy-max/ghaction-github-pages@v3.1.0
#         with:
#           target_branch: output
#           build_dir: dist
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Generate Snake

on:
  # Run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *" 
  
  # Allows to manually run the job at any time
  workflow_dispatch:
  
  # Run on every push on the master branch
  push:
    branches:
      - master
    
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Generates a snake game from a GitHub user contributions graph, output a SVG animation at <svg_out_path>
      - name: Generate GitHub Contribution Grid Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake-light.svg
            dist/github-contribution-grid-snake-night.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Push the content of <build_dir> to a branch
      # The content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file>, or as GitHub Pages
      - name: Push GitHub Contribution Grid Snake to the Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          files: |
            github-contribution-grid-snake-light.svg
            github-contribution-grid-snake-night.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
